#!/bin/sh

# To generate PDFs that are somewhat OK you will need to have the Roboto and Roboto mono font families installed on your system
# https://fonts.google.com/specimen/Roboto
# https://fonts.google.com/specimen/Roboto+Mono

echo "-----Rebuilding documentation..."
echo "     > HTML"
echo "     > index.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/index.md -o documentation/index.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > about.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/about.md -o documentation/about.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > resources.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/resources.md -o documentation/resources.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > developer.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/developer.md -o documentation/developer.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > support.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/support.md -o documentation/support.html --lua-filter=documentation/source/pandocfilters/filter-html.lua









# Comment out next sections before generating docs for release
echo "     > markdowntest.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/markdowntest.md -o documentation/markdowntest.html --lua-filter=documentation/source/pandocfilters/filter-html.lua

echo "     > markdowntestpdf.html > markdowntest.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/markdowntest.md -o documentation/source/pdftemp/markdowntestpdf.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/markdowntestpdf.html documentation/pdf/markdowntest.pdf

echo "     > markdowntestps.md"
python3 documentation/source/makepsmd.py documentation/source/markdowntest.md documentation/source/productsite/markdowntestps.md

echo "-----Completed!"
