#!/bin/sh

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/CharisSIL-Regular.ufo -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/CharisSIL-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/CharisSIL-Bold.ufo       &
psfnormalize -p checkfix=fix source/CharisSIL-Italic.ufo     &
psfnormalize -p checkfix=fix source/CharisSIL-BoldItalic.ufo &
wait

# add building of composites here

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/CharisSILRoman.designspace source/CharisSILItalic.designspace

echo "-----Preflight completed!"
