#!/bin/sh

# sync/copy meta data.  No need to normalize since UFOstripChangedTime will do that
UFOsyncMeta source/CharisSIL-Regular.ufo

# Strip Glyphs changed time since otherwise every glyph shows as modified to git.
./tools/UFOstripChangedTime.py source/CharisSIL-Regular.ufo
./tools/UFOstripChangedTime.py source/CharisSIL-Italic.ufo
./tools/UFOstripChangedTime.py source/CharisSIL-Bold.ufo
./tools/UFOstripChangedTime.py source/CharisSIL-BoldItalic.ufo
