#!/bin/sh

echo "-----Fixing FontForge debris and normalizing UFOs..."
psffixffglifs source/CharisSIL-Regular.ufo -p checkfix=fix     &
psffixffglifs source/CharisSIL-Bold.ufo -p checkfix=fix        &
psffixffglifs source/CharisSIL-Italic.ufo -p checkfix=fix      &
psffixffglifs source/CharisSIL-BoldItalic.ufo -p checkfix=fix  &
wait

echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=fix -i source/glyph_data.csv source/CharisSIL-Regular.ufo -p backup=False -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/CharisSIL-Regular.ufo -p backup=False -x

# add building of composites here

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/CharisSILRoman.designspace source/CharisSILItalic.designspace

echo "-----Preflight completed!"
