#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo --nofea source/CharisSILRoman.glyphs source -l source/logs/glyphsexportR.log
psfglyphs2ufo --nofea source/CharisSILItalic.glyphs source -l source/logs/glyphsexportI.log

# update psnames and sort order in Regular, which also normalizes it
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/CharisSIL-Regular.ufo -l source/logs/psnames.log
psfsetglyphorder --header sort_final_cdg -i source/glyph_data.csv source/CharisSIL-Regular.ufo -l source/logs/sortorder.log

# normalize other family members
psfnormalize -p checkfix=fix source/CharisSIL-Bold.ufo -l source/logs/normB.log
psfnormalize -p checkfix=fix source/CharisSIL-Italic.ufo -l source/logs/normI.log
psfnormalize -p checkfix=fix source/CharisSIL-BoldItalic.ufo -l source/logs/normBI.log

# copy psnames and glyphorder and any other updates to all fonts
psfsyncmasters source/CharisSILRoman.designspace source/CharisSILItalic.designspace -l source/logs/sync.log

 # Fix problem with non-spacing marks due to glyphsLib bug
psfremovegliflibkeys source/CharisSIL-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixR.log
psfremovegliflibkeys source/CharisSIL-Bold.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixB.log
psfremovegliflibkeys source/CharisSIL-Italic.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixI.log
psfremovegliflibkeys source/CharisSIL-BoldItalic.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixBI.log
