#!/bin/sh

# update psnames and sort order in Regular, which also normalizes it
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/CharisSIL-Regular.ufo -l source/logs/psnames.log
psfsetglyphorder --header sort_final_cdg -i source/glyph_data.csv source/CharisSIL-Regular.ufo -l source/logs/sortorder.log

# normalize other family members
psfnormalize -p checkfix=fix source/CharisSIL-Bold.ufo -l source/logs/normB.log
psfnormalize -p checkfix=fix source/CharisSIL-Italic.ufo -l source/logs/normI.log
psfnormalize -p checkfix=fix source/CharisSIL-BoldItalic.ufo -l source/logs/normBI.log

# copy psnames and glyphorder and any other updates to all fonts
psfsyncmasters source/CharisSILRoman.designspace source/CharisSILItalic.designspace -l source/logs/sync.log
